#### 예외처리

에러와 예외

- 어떤 원인에 의해 오동작하거나 비정상적으로 종료되는 경우

- 심각도에 따른 분류
  
  - error
    
    메모리 부족, 일단 발생하면 복구할 수 없는 상황
    
    디버깅 필요
  
  - exception
    
    읽으려는 파일이 없거나 네트워크 연결이 안 되는 등
    
    프로그램 코드에 의해 수습될 수 있는 상황

- 예외 처리란?
  
  예외 발생 시 프로그램의 비정상 종료를 막고 정상적인 실행 상태를 유지하는 것
  
  -> 예외의 감지 및 예외 발생 시 동작할 코드 작성 필요



**예외 클래스의 계층**

- checked exception
  
  예외에 대한 대처 코드가 없으면 컴파일이 진행되지 않음

- unchecked exception(RuntimeException의 하위 클래스)
  
  예외에 대한 대처 코드가 없더라도 컴파일은 진행됨



**try~catch 구문**

try > 예외가 발생할 수 있는 코드

catch > 던진 예외를 받아서 예외가 발생했을 때 처리할 코드



##### exception객체의 정보 활용

- Throwable의 주요 메서드
  
  public String getMessage() : 발생된 예외에 대한 구체적인 메세지를 반환한다
  
  public Throwable getCause() : 예외의 원인이 되는 Throwable 객체 또는 null을 반환한다
  
  public void printStackTrace() : 예외가 발생된 메서드가 호출되기까지의 메서드 호출 스택을 출력한다. 디버깅의 수단으로 주로 사용된다.



##### try-catch문의 흐름

- try 블록에서 예외가 발생하면
  
  JVM이 해당 exception 클래스의 객체 생성 후 던짐
  
  던져진 예외를 처리할 수 있는 catch블록에서 받은 후 처리
  
  적당한 캐치 블록을 만나지 못하면 예외처리는 실패
  
  정상적으로 처리되면 블록을 벗어나 다음 문장 진행

- 예외 발생하지 않은 경우
  
  catch문을 거치지 않고  트라이-캐치 블록의 다음 흐름 문장을 실행



##### 다중 exception handling

하나의 try 블록에 여러개의 catch 블록 추가 가능



**다중 예외 처리를 이용한 checked Exception 처리**

- 처리하지 않으면 컴파일 불가

- 예외 처리는 가능한 구체적으로 진행

- 발생하는 예외들을 하나로 처리하기(쉽지않음..)
  
  - 가급적 예외상황별로 처리하는 것을 권장

- 심각하지 않은 예외를 굳이 세분화 해서 처리하는 것도 낭비
  
  - "|"를 이용해 하나의 catch구문에서 상속관계가 없는 여러 개의 exception 처리

- 계층을 이용한 예외의 처리
  
  FileNotFoundException의 상속 관계
  
  ```java
  java.lang.Object
      java.lang.Throwable
          java.lang.Exception
              java.lang.IOException
                  java.lang.FileNotFoundException
  ```
  
  맨 아래에서부터..



##### try~catch~finally 구문을 이용한 예외 처리

- finally는 예외 발생 여부와 상관 없이 언제나 실행
  
  중간에 return을 만나는 경우도 finally블록을 먼저 수행 후 리턴 실행
  
  주요 목적 : try블록에서 사용한 리소스 반납



##### try-with-resources

- JDK 1.7이상은 리소스의 자동 close처리

- try선언문에 선언된 객체들에 대해 자동 close 호출
  
  단, 해당 객체들이 AutoCloseable interface를 구현할 것...



##### Throws 활용

예외를 강제로 발생시키는 것..

```java
throw new 발생시킬 예외; 
```

왜 강제로 발생시킬까? 예외를 한번 더 처리하기 위함

throw키워드를 이용해서 내 메서드 안에서 일어날 수 있는 예외를 나를 호출한 곳으로 전가시킴

runtime exception은 throws 하지 않아도 전달되지만 결국은 try~catch로 처리해야 함



##### 로그 분석과 예외의 추적

Throwable의 printStackTrace는 메서드 호출 스택 정보 조회 가능

최초 호출 메서드에서부터 예외 발생 메서드까지의 스택 정보 출력

꼭 확인해야할 정보

- 예외 종류

- 원인

- 디버깅 출발점



##### 메서드 재정의와 throws

메서드 재정의 시 조상클래스 메서드가 던지는 예외보다 부모 예외를 던질 수 없다.


